version: "3"

services:
  influxdb:
    image: influxdb:1.8
    restart: unless-stopped
    volumes:
      - influxdb-volume:/var/lib/influxdb
  zenoh-router:
    build: .
    volumes:
      - ./config.json5:/config.json5
    environment:
      RUST_LOG: zenoh=info
    ports:
      - 7448:7447/tcp
      - 7448:7447/udp
      - 8090:8000
    depends_on:
      - influxdb

volumes:
  influxdb-volume: