version: "3"

services:
  influxdb:
    image: influxdb:1.8
    restart: unless-stopped
    # environment:
    #   INFLUXDB_ADMIN_USER: root
    #   INFLUXDB_ADMIN_PASSWORD: root
    #   INFLUXDB_USER: user
    #   INFLUXDB_USER_PASSWORD: user
    volumes:
      - influxdb-volume:/var/lib/influxdb
    # ports:
    #   - 8086:8086
  zenoh-router:
    build: .
    volumes:
      - ./config.json5:/config.json5
    environment:
      RUST_LOG: zenoh=info
    ports:
      - 7448:7447/tcp
      - 7448:7447/udp
      - 8090:8000
    depends_on:
      - influxdb
      - grafana

  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  grafana-data:

  influxdb-volume: